version: "3"

vars:
  BINARY_NAME: motophoto

tasks:
  dev:
    desc: Start all development servers
    deps: [dev-backend, dev-frontend]

  dev-backend:
    desc: Start backend with hot-reload
    internal: true
    cmds:
      - air -build.send_interrupt true

  dev-frontend:
    desc: Start SvelteKit dev server
    internal: true
    dir: web
    cmds:
      - bun run dev

  build:
    desc: Full production build
    deps: [build-frontend, build-backend]

  build-backend:
    desc: Build Go binary
    cmds:
      - go build -o {{.BINARY_NAME}} .

  build-frontend:
    desc: Build SvelteKit for production
    dir: web
    cmds:
      - bun install --frozen-lockfile
      - bun run build

  check:
    desc: Run type checks and linting
    cmds:
      - go vet ./...
      - cd web && bun run check

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run ./...
      - cd web && bun run lint

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  db-migrate:
    desc: Run database migrations
    cmds:
      - echo "TODO - migration runner"

  generate:
    desc: Run sqlc code generation
    cmds:
      - sqlc generate

  docker-build:
    desc: Build Docker image
    cmds:
      - docker build -t motophoto .

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BINARY_NAME}} web/build tmp/

  default:
    desc: Default task (runs dev)
    cmds:
      - task: dev
