// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (id, photographer_id, slug, name, sport, location, description, tags, status, date, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, photographer_id, slug, name, sport, location, description, tags, status, date, cover_photo_id, sort_order, created_at, updated_at
`

type CreateEventParams struct {
	ID             string      `json:"id"`
	PhotographerID string      `json:"photographer_id"`
	Slug           string      `json:"slug"`
	Name           string      `json:"name"`
	Sport          string      `json:"sport"`
	Location       pgtype.Text `json:"location"`
	Description    pgtype.Text `json:"description"`
	Tags           []string    `json:"tags"`
	Status         EventStatus `json:"status"`
	Date           pgtype.Date `json:"date"`
	SortOrder      int32       `json:"sort_order"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.ID,
		arg.PhotographerID,
		arg.Slug,
		arg.Name,
		arg.Sport,
		arg.Location,
		arg.Description,
		arg.Tags,
		arg.Status,
		arg.Date,
		arg.SortOrder,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.PhotographerID,
		&i.Slug,
		&i.Name,
		&i.Sport,
		&i.Location,
		&i.Description,
		&i.Tags,
		&i.Status,
		&i.Date,
		&i.CoverPhotoID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT e.id, e.photographer_id, e.slug, e.name, e.sport, e.location, e.description, e.tags, e.status, e.date, e.cover_photo_id, e.sort_order, e.created_at, e.updated_at,
       (SELECT count(*) FROM photos p
        JOIN galleries g ON g.id = p.gallery_id
        WHERE g.event_id = e.id AND p.deleted_at IS NULL)::bigint AS photo_count
FROM events e
WHERE e.id = $1 OR e.slug = $1
`

type GetEventRow struct {
	ID             string             `json:"id"`
	PhotographerID string             `json:"photographer_id"`
	Slug           string             `json:"slug"`
	Name           string             `json:"name"`
	Sport          string             `json:"sport"`
	Location       pgtype.Text        `json:"location"`
	Description    pgtype.Text        `json:"description"`
	Tags           []string           `json:"tags"`
	Status         EventStatus        `json:"status"`
	Date           pgtype.Date        `json:"date"`
	CoverPhotoID   pgtype.Text        `json:"cover_photo_id"`
	SortOrder      int32              `json:"sort_order"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	PhotoCount     int64              `json:"photo_count"`
}

func (q *Queries) GetEvent(ctx context.Context, idOrSlug string) (GetEventRow, error) {
	row := q.db.QueryRow(ctx, getEvent, idOrSlug)
	var i GetEventRow
	err := row.Scan(
		&i.ID,
		&i.PhotographerID,
		&i.Slug,
		&i.Name,
		&i.Sport,
		&i.Location,
		&i.Description,
		&i.Tags,
		&i.Status,
		&i.Date,
		&i.CoverPhotoID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhotoCount,
	)
	return i, err
}

const getEventOwner = `-- name: GetEventOwner :one
SELECT photographer_id FROM events WHERE id = $1
`

func (q *Queries) GetEventOwner(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getEventOwner, id)
	var photographer_id string
	err := row.Scan(&photographer_id)
	return photographer_id, err
}

const listEvents = `-- name: ListEvents :many
SELECT e.id, e.photographer_id, e.slug, e.name, e.sport, e.location, e.description, e.tags, e.status, e.date, e.cover_photo_id, e.sort_order, e.created_at, e.updated_at,
       (SELECT count(*) FROM photos p
        JOIN galleries g ON g.id = p.gallery_id
        WHERE g.event_id = e.id AND p.deleted_at IS NULL)::bigint AS photo_count
FROM events e
WHERE e.status = 'published'
  AND ($1::int IS NULL
       OR (e.sort_order, e.id) > ($1::int, $2::text))
ORDER BY e.sort_order, e.id
LIMIT $3::int
`

type ListEventsParams struct {
	CursorSortOrder pgtype.Int4 `json:"cursor_sort_order"`
	CursorID        pgtype.Text `json:"cursor_id"`
	LimitVal        int32       `json:"limit_val"`
}

type ListEventsRow struct {
	ID             string             `json:"id"`
	PhotographerID string             `json:"photographer_id"`
	Slug           string             `json:"slug"`
	Name           string             `json:"name"`
	Sport          string             `json:"sport"`
	Location       pgtype.Text        `json:"location"`
	Description    pgtype.Text        `json:"description"`
	Tags           []string           `json:"tags"`
	Status         EventStatus        `json:"status"`
	Date           pgtype.Date        `json:"date"`
	CoverPhotoID   pgtype.Text        `json:"cover_photo_id"`
	SortOrder      int32              `json:"sort_order"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	PhotoCount     int64              `json:"photo_count"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.CursorSortOrder, arg.CursorID, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsRow{}
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.PhotographerID,
			&i.Slug,
			&i.Name,
			&i.Sport,
			&i.Location,
			&i.Description,
			&i.Tags,
			&i.Status,
			&i.Date,
			&i.CoverPhotoID,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PhotoCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events SET
    name        = COALESCE($1, name),
    slug        = COALESCE($2, slug),
    sport       = COALESCE($3, sport),
    location    = COALESCE($4, location),
    description = COALESCE($5, description),
    tags        = COALESCE($6, tags),
    status      = COALESCE($7, status),
    date        = COALESCE($8, date),
    sort_order  = COALESCE($9, sort_order),
    updated_at  = now()
WHERE id = $10
RETURNING id, photographer_id, slug, name, sport, location, description, tags, status, date, cover_photo_id, sort_order, created_at, updated_at
`

type UpdateEventParams struct {
	Name        pgtype.Text     `json:"name"`
	Slug        pgtype.Text     `json:"slug"`
	Sport       pgtype.Text     `json:"sport"`
	Location    pgtype.Text     `json:"location"`
	Description pgtype.Text     `json:"description"`
	Tags        []string        `json:"tags"`
	Status      NullEventStatus `json:"status"`
	Date        pgtype.Date     `json:"date"`
	SortOrder   pgtype.Int4     `json:"sort_order"`
	ID          string          `json:"id"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.Name,
		arg.Slug,
		arg.Sport,
		arg.Location,
		arg.Description,
		arg.Tags,
		arg.Status,
		arg.Date,
		arg.SortOrder,
		arg.ID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.PhotographerID,
		&i.Slug,
		&i.Name,
		&i.Sport,
		&i.Location,
		&i.Description,
		&i.Tags,
		&i.Status,
		&i.Date,
		&i.CoverPhotoID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
