// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: galleries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGallery = `-- name: CreateGallery :one
INSERT INTO galleries (id, event_id, slug, name, description, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, event_id, slug, name, description, sort_order, cover_photo_id, created_at, updated_at
`

type CreateGalleryParams struct {
	ID          string      `json:"id"`
	EventID     string      `json:"event_id"`
	Slug        string      `json:"slug"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	SortOrder   int32       `json:"sort_order"`
}

func (q *Queries) CreateGallery(ctx context.Context, arg CreateGalleryParams) (Gallery, error) {
	row := q.db.QueryRow(ctx, createGallery,
		arg.ID,
		arg.EventID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.SortOrder,
	)
	var i Gallery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CoverPhotoID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGallery = `-- name: DeleteGallery :exec
DELETE FROM galleries WHERE id = $1 AND event_id = $2
`

type DeleteGalleryParams struct {
	ID      string `json:"id"`
	EventID string `json:"event_id"`
}

func (q *Queries) DeleteGallery(ctx context.Context, arg DeleteGalleryParams) error {
	_, err := q.db.Exec(ctx, deleteGallery, arg.ID, arg.EventID)
	return err
}

const getGallery = `-- name: GetGallery :one
SELECT g.id, g.event_id, g.slug, g.name, g.description, g.sort_order, g.cover_photo_id, g.created_at, g.updated_at,
       (SELECT count(*) FROM photos p WHERE p.gallery_id = g.id AND p.deleted_at IS NULL)::bigint AS photo_count
FROM galleries g
WHERE g.id = $1 AND g.event_id = $2
`

type GetGalleryParams struct {
	ID      string `json:"id"`
	EventID string `json:"event_id"`
}

type GetGalleryRow struct {
	ID           string             `json:"id"`
	EventID      string             `json:"event_id"`
	Slug         string             `json:"slug"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	SortOrder    int32              `json:"sort_order"`
	CoverPhotoID pgtype.Text        `json:"cover_photo_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	PhotoCount   int64              `json:"photo_count"`
}

func (q *Queries) GetGallery(ctx context.Context, arg GetGalleryParams) (GetGalleryRow, error) {
	row := q.db.QueryRow(ctx, getGallery, arg.ID, arg.EventID)
	var i GetGalleryRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CoverPhotoID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhotoCount,
	)
	return i, err
}

const listGalleriesByEvent = `-- name: ListGalleriesByEvent :many
SELECT g.id, g.event_id, g.slug, g.name, g.description, g.sort_order, g.cover_photo_id, g.created_at, g.updated_at,
       (SELECT count(*) FROM photos p WHERE p.gallery_id = g.id AND p.deleted_at IS NULL)::bigint AS photo_count
FROM galleries g
WHERE g.event_id = $1
ORDER BY g.sort_order, g.id
`

type ListGalleriesByEventRow struct {
	ID           string             `json:"id"`
	EventID      string             `json:"event_id"`
	Slug         string             `json:"slug"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	SortOrder    int32              `json:"sort_order"`
	CoverPhotoID pgtype.Text        `json:"cover_photo_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	PhotoCount   int64              `json:"photo_count"`
}

func (q *Queries) ListGalleriesByEvent(ctx context.Context, eventID string) ([]ListGalleriesByEventRow, error) {
	rows, err := q.db.Query(ctx, listGalleriesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGalleriesByEventRow{}
	for rows.Next() {
		var i ListGalleriesByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.CoverPhotoID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PhotoCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGallery = `-- name: UpdateGallery :one
UPDATE galleries SET
    name        = COALESCE($1, name),
    slug        = COALESCE($2, slug),
    description = COALESCE($3, description),
    sort_order  = COALESCE($4, sort_order),
    updated_at  = now()
WHERE id = $5 AND event_id = $6
RETURNING id, event_id, slug, name, description, sort_order, cover_photo_id, created_at, updated_at
`

type UpdateGalleryParams struct {
	Name        pgtype.Text `json:"name"`
	Slug        pgtype.Text `json:"slug"`
	Description pgtype.Text `json:"description"`
	SortOrder   pgtype.Int4 `json:"sort_order"`
	ID          string      `json:"id"`
	EventID     string      `json:"event_id"`
}

func (q *Queries) UpdateGallery(ctx context.Context, arg UpdateGalleryParams) (Gallery, error) {
	row := q.db.QueryRow(ctx, updateGallery,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.SortOrder,
		arg.ID,
		arg.EventID,
	)
	var i Gallery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CoverPhotoID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
