// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmPhoto = `-- name: ConfirmPhoto :one
UPDATE photos SET
    width      = $3,
    height     = $4,
    size_bytes = $5,
    taken_at   = $6,
    status     = 'ready',
    updated_at = now()
WHERE id = $1 AND gallery_id = $2 AND status = 'pending'
RETURNING id, gallery_id, storage_key, preview_key, filename, content_type, size_bytes, width, height, sort_order, exif_data, taken_at, deleted_at, created_at, updated_at, status
`

type ConfirmPhotoParams struct {
	ID        string             `json:"id"`
	GalleryID string             `json:"gallery_id"`
	Width     pgtype.Int4        `json:"width"`
	Height    pgtype.Int4        `json:"height"`
	SizeBytes int64              `json:"size_bytes"`
	TakenAt   pgtype.Timestamptz `json:"taken_at"`
}

func (q *Queries) ConfirmPhoto(ctx context.Context, arg ConfirmPhotoParams) (Photo, error) {
	row := q.db.QueryRow(ctx, confirmPhoto,
		arg.ID,
		arg.GalleryID,
		arg.Width,
		arg.Height,
		arg.SizeBytes,
		arg.TakenAt,
	)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.GalleryID,
		&i.StorageKey,
		&i.PreviewKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.SortOrder,
		&i.ExifData,
		&i.TakenAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const createPhoto = `-- name: CreatePhoto :one
INSERT INTO photos (id, gallery_id, storage_key, preview_key, filename, content_type, size_bytes, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'pending')
RETURNING id, gallery_id, storage_key, preview_key, filename, content_type, size_bytes, width, height, sort_order, exif_data, taken_at, deleted_at, created_at, updated_at, status
`

type CreatePhotoParams struct {
	ID          string `json:"id"`
	GalleryID   string `json:"gallery_id"`
	StorageKey  string `json:"storage_key"`
	PreviewKey  string `json:"preview_key"`
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
	SizeBytes   int64  `json:"size_bytes"`
}

func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error) {
	row := q.db.QueryRow(ctx, createPhoto,
		arg.ID,
		arg.GalleryID,
		arg.StorageKey,
		arg.PreviewKey,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
	)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.GalleryID,
		&i.StorageKey,
		&i.PreviewKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.SortOrder,
		&i.ExifData,
		&i.TakenAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const getPhoto = `-- name: GetPhoto :one
SELECT id, gallery_id, storage_key, preview_key, filename, content_type, size_bytes, width, height, sort_order, exif_data, taken_at, deleted_at, created_at, updated_at, status FROM photos
WHERE id = $1 AND gallery_id = $2
`

type GetPhotoParams struct {
	ID        string `json:"id"`
	GalleryID string `json:"gallery_id"`
}

func (q *Queries) GetPhoto(ctx context.Context, arg GetPhotoParams) (Photo, error) {
	row := q.db.QueryRow(ctx, getPhoto, arg.ID, arg.GalleryID)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.GalleryID,
		&i.StorageKey,
		&i.PreviewKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.SortOrder,
		&i.ExifData,
		&i.TakenAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const listPhotosByGallery = `-- name: ListPhotosByGallery :many
SELECT id, gallery_id, storage_key, preview_key, filename, content_type, size_bytes, width, height, sort_order, exif_data, taken_at, deleted_at, created_at, updated_at, status
FROM photos
WHERE gallery_id = $1 AND deleted_at IS NULL AND status = 'ready'
ORDER BY sort_order, id
`

func (q *Queries) ListPhotosByGallery(ctx context.Context, galleryID string) ([]Photo, error) {
	rows, err := q.db.Query(ctx, listPhotosByGallery, galleryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Photo{}
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.GalleryID,
			&i.StorageKey,
			&i.PreviewKey,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.SortOrder,
			&i.ExifData,
			&i.TakenAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
