// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

export interface ErrorResponse {
  error: string;
}
export interface ListResponse<T extends any> {
  next_cursor?: string;
  data: T[];
}
export interface ItemResponse<T extends any> {
  data: T;
}
export interface EventResponse {
  location?: string;
  description?: string;
  date?: string;
  id: string;
  slug: string;
  name: string;
  sport: string;
  status: string;
  galleries?: GalleryResponse[];
  tags: string[];
  photo_count: number /* int64 */;
}
export interface GalleryResponse {
  earliest_photo_time?: string;
  latest_photo_time?: string;
  description?: string;
  id: string;
  slug: string;
  name: string;
  photo_count: number /* int64 */;
  sort_order: number /* int32 */;
}
export interface CreateEventRequest {
  location?: string;
  description?: string;
  date?: string;
  status?: string;
  name: string;
  slug: string;
  sport: string;
  tags: string[];
}
export interface UpdateEventRequest {
  tags?: string[];
  name?: string;
  slug?: string;
  sport?: string;
  location?: string;
  description?: string;
  date?: string;
  status?: string;
  sort_order?: number /* int32 */;
}
export interface CreateGalleryRequest {
  description?: string;
  sort_order?: number /* int32 */;
  name: string;
  slug: string;
}
export interface UpdateGalleryRequest {
  name?: string;
  slug?: string;
  description?: string;
  sort_order?: number /* int32 */;
}
export interface PhotoResponse {
  taken_at?: string;
  width?: number /* int32 */;
  height?: number /* int32 */;
  id: string;
  filename: string;
  content_type: string;
  preview_url: string;
  size_bytes: number /* int64 */;
}
export interface InitUploadRequest {
  filename: string;
  content_type: string;
  size_bytes: number /* int64 */;
}
export interface InitUploadResponse {
  photo_id: string;
  upload_url: string;
}
export interface LoginRequest {
  email: string;

  password: string;
}
export interface RegisterRequest {
  email: string;

  password: string;
  display_name: string;
  role: string;
}
export interface UserResponse {
  id: string;
  email: string;
  display_name: string;
  role: string;
}
