// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

export interface Event {
  name: string;
  sport: string;
  location: string;
  date: string;
  description: string;
  tags: string[];
  id: number /* int */;
  photo_count: number /* int */;
  galleries: number /* int */;
}
