import { menuAnatomy } from '@ark-ui/svelte/anatomy';
import { defineSlotRecipe } from '@pandacss/dev';

export const menuRecipe = defineSlotRecipe({
	className: 'menu',
	slots: menuAnatomy.keys(),
	base: {
		trigger: {
			display: 'inline-flex',
			alignItems: 'center',
			justifyContent: 'center',
			gap: '1.5',
			borderRadius: 'md',
			fontSize: 'sm',
			fontWeight: 'medium',
			whiteSpace: 'nowrap',
			transition: 'all',
			transitionDuration: '150ms',
			cursor: 'pointer',
			userSelect: 'none',
			outline: 'none',
			textDecoration: 'none',
			bg: 'transparent',
			color: 'fg',
			borderWidth: '1px',
			borderColor: 'border',
			h: '8',
			px: '3',
			_disabled: { opacity: 0.5, pointerEvents: 'none' },
			_focusVisible: {
				outlineWidth: '2px',
				outlineColor: 'primary',
				outlineOffset: '2px',
				outlineStyle: 'solid',
			},
			_hover: { bg: 'bg.muted' },
			'& svg': {
				pointerEvents: 'none',
				flexShrink: 0,
				width: '1em',
				height: '1em',
			},
		},
		positioner: {
			zIndex: '50',
		},
		content: {
			bg: 'bg',
			borderWidth: '1px',
			borderColor: 'border',
			borderRadius: 'lg',
			boxShadow: 'lg',
			outline: 'none',
			p: '1',
			minW: '10rem',
			_open: {
				animation: 'fade-in 120ms ease-out',
			},
			_closed: {
				animation: 'fade-out 100ms ease-in',
			},
		},
		item: {
			display: 'flex',
			alignItems: 'center',
			gap: '2',
			px: '2',
			py: '1.5',
			borderRadius: 'md',
			fontSize: 'sm',
			cursor: 'pointer',
			outline: 'none',
			userSelect: 'none',
			textDecoration: 'none',
			color: 'fg',
			transition: 'background',
			transitionDuration: '100ms',
			_hover: { bg: 'bg.muted' },
			_highlighted: { bg: 'bg.muted' },
			_disabled: { opacity: 0.5, pointerEvents: 'none', cursor: 'not-allowed' },
			'& svg': {
				pointerEvents: 'none',
				flexShrink: 0,
				width: '1em',
				height: '1em',
				color: 'fg.muted',
			},
		},
		itemGroupLabel: {
			px: '2',
			py: '1',
			fontSize: 'xs',
			fontWeight: 'semibold',
			color: 'fg.muted',
			textTransform: 'uppercase',
			letterSpacing: 'wider',
		},
		separator: {
			h: '1px',
			bg: 'border',
			my: '1',
			mx: '-1',
		},
		indicator: {
			display: 'inline-flex',
			alignItems: 'center',
			justifyContent: 'center',
			'& svg': {
				width: '1em',
				height: '1em',
				transition: 'transform',
				transitionDuration: '200ms',
			},
			_open: {
				'& svg': { transform: 'rotate(180deg)' },
			},
		},
	},
});
